# Numpy 

In [2]:
import numpy as np

In [3]:
np.__version__ # attibute to check numpy version

'2.3.5'

In [4]:
arr=[1,2,3,4,5]
arr

[1, 2, 3, 4, 5]

In [5]:
narr=np.array(arr)
narr

array([1, 2, 3, 4, 5])

In [6]:
arr_2d=[[1,2,3],[4,5,6],[7,8,9]]
narr_2d=np.array(arr_2d)
narr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.arange(10,15,2)

array([10, 12, 14])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4)) # 3 rows and 4 columns of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((2,3,4)) # 3D array with 2 blocks, 3 rows and 4 columns

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
np.linspace(start=10,stop=20,num=5) # 5 values between 0 and 1

array([10. , 12.5, 15. , 17.5, 20. ])

# Part two: Random Numbers

In [13]:
np.eye(4) # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(3,4) # random values in a 3x4 array between 0 and 1

array([[0.75137623, 0.55380036, 0.93783553, 0.85494775],
       [0.29793481, 0.19657376, 0.67260757, 0.87767333],
       [0.31849241, 0.30492369, 0.99027186, 0.31549256]])

In [ ]:
np.random.rand() # single random value between 0 and 1

0.5362850334223579

In [16]:
np.random.randn(4,5) # random values from standard normal distribution in a 4x5 array

array([[-2.23044184,  0.10784893, -0.46072387,  0.13502149,  0.23581927],
       [-0.13338364, -0.01467769, -0.51259061,  2.57018655,  0.65624858],
       [ 0.24847494,  0.95209037,  0.93204199, -2.34313014, -1.27721809],
       [ 1.20693427, -1.69339453,  1.3455704 , -1.40417013, -0.1275112 ]])

In [17]:
np.random.randint(10,21,size=(3,4)) # random integers between 10 and 20 in a 3x4 array

array([[10, 15, 14, 12],
       [12, 18, 18, 17],
       [18, 17, 20, 15]], dtype=int32)

In [20]:
rarr=np.random.randint(10,21,size=[5,2,3])

In [21]:
rarr.shape # shape of the array

(5, 2, 3)

In [24]:
rarr_2d=rarr.reshape(6,5)

In [27]:
rarr.shape # shape of the array
rarr_2d.shape # shape of the reshaped array

(6, 5)

In [29]:
# usseful methods
rarr_2d.max() # maximum value in the array

np.int32(20)

In [30]:
rarr_2d.min() # minimum value in the array

np.int32(10)

In [32]:
rarr_1d=rarr_2d.reshape(30)

In [33]:
rarr_1d.argmax()

np.int64(6)

In [34]:
rarr_1d

array([14, 14, 10, 15, 19, 13, 20, 13, 18, 11, 20, 17, 15, 16, 10, 18, 14,
       15, 12, 12, 13, 10, 12, 11, 20, 12, 14, 17, 10, 18], dtype=int32)

In [35]:
rarr_1d[2]

np.int32(10)

# Indexing and slicing

In [44]:
arr=np.arange(20)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
arr[0]

np.int64(0)

In [47]:
arr[-1]

np.int64(19)

In [48]:
arr[1:8] # slicing from index 1 to 7

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
arr[:7:2]

array([0, 2, 4, 6])

In [57]:
arr_2=arr[7:17]

In [58]:
arr_2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
arr_2[4]=99 
arr_2

array([ 7,  8,  9, 10, 99, 12, 13, 14, 15, 16])

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 99, 12, 13, 14, 15, 16,
       17, 18, 19])

In [61]:
arr_2[:]=99
arr_2


array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       17, 18, 19])

In [69]:

# array copy
arr_3=arr_2[2:6].copy()

In [70]:
arr_3

array([99, 99, 99, 99])