# Numpy 

In [1]:
import numpy as np

In [ ]:
np.__version__ # attibute to check numpy version

'2.3.5'

In [3]:
arr=[1,2,3,4,5]
arr

[1, 2, 3, 4, 5]

In [5]:
narr=np.array(arr)
narr

array([1, 2, 3, 4, 5])

In [7]:
arr_2d=[[1,2,3],[4,5,6],[7,8,9]]
narr_2d=np.array(arr_2d)
narr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(10,15,2)

array([10, 12, 14])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4)) # 3 rows and 4 columns of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2,3,4)) # 3D array with 2 blocks, 3 rows and 4 columns

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
np.linspace(start=10,stop=20,num=5) # 5 values between 0 and 1

array([10. , 12.5, 15. , 17.5, 20. ])