# Numpy and Inbuilt Functions Tutorial

In [2]:
# initially lets import numpy
import numpy as np

In [3]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.shape

(5,)

In [56]:
# Two Dimentional Array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,5,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 5, 6, 8, 9]])

In [12]:
arr.shape #rows and column

(3, 5)

In [13]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 5],
       [6, 8, 9]])

In [15]:
arr.shape

(3, 5)

# Indexing

In [70]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [53]:
arr[3]

np.int64(4)

In [54]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[0:2,:] # Row : Column

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [58]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [24]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [27]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [60]:
arr=np.arange(0,10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr=np.arange(0,10,step=2)

In [63]:
arr

array([0, 2, 4, 6, 8])

In [64]:
#LineSpace PRint how many point i want
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [80]:
# Copy function & Broadcasting
arr[3:]=100

In [81]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [86]:
arr1=arr.copy()

In [87]:
print(arr)
arr1[3:]=500
print(arr1)

[  1   2   3 100 100 100 100 100 100]
[  1   2   3 500 500 500 500 500 500]


In [88]:
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

# Some condtion very useful in Exploratory Data Analysis

In [90]:
val=2
arr<2
arr*2

array([  2,   4,   6, 200, 200, 200, 200, 200, 200])

In [93]:
# Print Exact Value 
arr[arr<300]

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [95]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [96]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
# Random ditribution
np.random.rand(3,3)

array([[0.42587506, 0.77061674, 0.82617672],
       [0.23692322, 0.94809644, 0.92288681],
       [0.0327589 , 0.28338107, 0.91847871]])

In [99]:
arr_ex=np.random.randn(4,4)

In [100]:
arr_ex

array([[0.01750124, 0.56044939, 0.18091692, 0.76698827],
       [0.25262286, 0.70912006, 0.27650474, 0.49940011],
       [0.88029759, 0.55680892, 0.87669873, 0.80614272],
       [0.76824074, 0.513088  , 0.40178385, 0.14675799]])

In [104]:
!pip install seaborn

In [108]:
np.random.randint(0,100,8)

array([ 7, 57, 19, 97, 63, 30, 52, 15])

In [110]:
np.random.random_sample((1,5))

array([[0.6249153 , 0.18585678, 0.50618861, 0.64088443, 0.51650632]])