# Numpy

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [6]:
## Create array using numpy
# create a 1d array
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [9]:
# Reshape in 2d 
arr2=np.array([1,2,3,4,5,6])
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
# 2d Array
arr2=np.array([[1,2,3,4,5],[2,3,5,6,7]])
print(arr2.shape)
arr2

(2, 5)


array([[1, 2, 3, 4, 5],
       [2, 3, 5, 6, 7]])

In [12]:
# arange Function
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
# Ones function
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
# identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# attiributes of numpy array
arr=np.array([[1,2,3],[4,5,6]])
print("Array\n", arr)
print("Array Dimensions: ", arr.ndim)
print("Array Shape: ", arr.shape)
print("Array Size: ", arr.size)
print("Array Data Type: ", arr.dtype)
print("Item Size :",arr.itemsize)

Array
 [[1 2 3]
 [4 5 6]]
Array Dimensions:  2
Array Shape:  (2, 3)
Array Size:  6
Array Data Type:  int64
Item Size : 8


In [19]:
# numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element wise addition
print("Addition: ", arr1 + arr2)

# Element wise subtraction
print("Subtraction: ", arr1 - arr2)
# Element wise multiplication
print("Multiplication: ", arr1 * arr2)
# Element wise division
print("Division: ", arr2 / arr1)


Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [10. 10. 10. 10. 10.]


In [20]:
# Universal Functions
arr=np.array([1,2,3,4,5,6])

# Square root
print("Square Root: ", np.sqrt(arr))

## Exponential
print("Exponential: ", np.exp(arr))

# sine
print("Sine: ", np.sin(arr))

# NAtural Logarithm
print("Natural Logarithm: ", np.log(arr))



Square Root:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
Sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural Logarithm:  [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [21]:
# array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr[0][1]

np.int64(2)

In [25]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [27]:
print(arr[0:2,1:])

[[2 3 4]
 [6 7 8]]


In [30]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [34]:
# Modifying array elements
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0,0]=10
arr

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
arr[1:]=100
arr

array([[ 10,   2,   3],
       [100, 100, 100],
       [100, 100, 100]])

In [36]:
# Statistical concepts with numpy- normalization
# to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5,6,7,8,9,10])

# Calculate mean and standard deviation
mean=data.mean()
std=data.std()
# Normalize the data
normalized_data=(data - mean)/std # standard normal distribution
print("Normalized Data: ", normalized_data)


Normalized Data:  [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [37]:
# calculte mean meadian standard deviation and variance
data=np.array([1,2,3,4,5,6,7,8,9,10])

# mean
mean=data.mean()
print("Mean: ", mean)

# median
median=np.median(data)
print("Median: ", median)

# standard deviation
std=data.std()
print("Standard Deviation: ", std)

# variance
variance=data.var()
print("Variance: ", variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [42]:
# Logical operations with numpy arrays
arr=np.array([1,2,3,4,5,6,7,8,9,10])
# elements greater than 5
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8])